### ISSUE TITLE
SyntaxError: E:\test\node_modules\watchpack\lib\chokidar.js: 'return' outside of function (4:2)

### ISSUE THREAD

**Issue by jawadzahoor72** [paulmillr/chokidar#1033]
try {
  3 |   module.exports = require("chokidar"); {
> 4 |           return;
    |           ^
  5 |   }
  6 | } catch(e) {
  7 |   v3Err = e;
    at Object._raise (E:\test\node_modules\@babel\parser\src\parser\error.js:60:45)
    at Object.raiseWithData (E:\test\node_modules\@babel\parser\src\parser\error.js:55:17)
    at Object.raise (E:\test\node_modules\@babel\parser\src\parser\error.js:39:17)
    at Object.parseReturnStatement (E:\test\node_modules\@babel\parser\src\parser\statement.js:563:12)
    at Object.parseStatementContent (E:\test\node_modules\@babel\parser\src\parser\statement.js:197:21)
    at Object.parseStatement (E:\test\node_modules\@babel\parser\src\parser\statement.js:151:17)
    at Object.parseBlockOrModuleBlockBody (E:\test\node_modules\@babel\parser\src\parser\statement.js:873:25)
    at Object.parseBlockBody (E:\test\node_modules\@babel\parser\src\parser\statement.js:843:10)
    at Object.parseBlock (E:\test\node_modules\@babel\parser\src\parser\statement.js:813:10)
    at Object.parseStatementContent (E:\test\node_modules\@babel\parser\src\parser\statement.js:218:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forbes-me@1.0.0 start: `pawjs --no-cache --config=./pawconfig.json --env=development start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forbes-me@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2020-08-17T09_19_41_742Z-debug.log

**Comment by nehasinghal3107** [comment]
Hey, I am too facing this issue , is this fixed ?

**Comment by jawadzahoor72** [comment]
@nehasinghal3107  .
it would not work on windows.  Try linux.. 
I installed Ubuntu 18.04 LTS and it runs without any error..

**Comment by nehasinghal3107** [comment]
@jawadzahoor72 tried this on ubuntu only, not working for me. is there a fix or just the platform issue?

**Comment by nehasinghal3107** [comment]
Ubuntu 18.04 LTS this is my OS, its giving error.

**Comment by jawadzahoor72** [comment]
@nehasinghal3107 please check for babelrc file.. add this one..


`
.babelrc
{
  "loose": ["es6.modules"]
}`

**Comment by kri7217** [comment]
@jawadzahoor72  
under which preset or plugin i need to use { "loose": ["es6.modules"] }
which preset/plugin i need to use in .babelrc

**Comment by jawadzahoor72** [comment]
@nehasinghal3107  
you should have babelrc in your src project directory.

**Comment by nehasinghal3107** [comment]
@jawadzahoor72 I have my file in same directory, tried with the following change

{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
    "es2016",
  ],
  "ignore":[ "node_modules"],
  "plugins": [
    "@babel/plugin-syntax-jsx",
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-proposal-export-namespace-from",
    "@babel/plugin-transform-runtime",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
   ["@babel/plugin-syntax-dynamic-import"],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ]   
  ]
}

but its still not working, request your help as m not getting sufficient solutions in other links. Thanks
