### ISSUE TITLE
Unhandled Exception emitted when Network Path disconnected

### ISSUE THREAD

**Issue by Abhishek150995** [paulmillr/chokidar#1074]
Chokidar Watcher is constantly watching a Network Directory path. But when I disconnect the VPN to break the connection. 

1) Error event is received. (watcher.on('error', (error) => { )
2) try to close earlier watcher and create new watcher 

Unhandled exception is thrown 

events.js:187
      throw er; // Unhandled 'error' event
      ^

**Error: UNKNOWN: unknown error, lstat** '\\192.168.224.9\data\FilewatcherTesting\STool3\S_R_S-Tool.csv'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (c:\Users\ve00ym113\Documents\SourceCodes\.....\node_modules\chokidar\index.js:641:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (c:\Users\ve00ym113\Documents\SourceCodes\......\node_modules\chokidar\lib\nodefs-handler.js:303:43)
    at ReaddirpStream.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  **errno: -4094,
  code: 'UNKNOWN',
  syscall: 'lstat',**
  path: '\\\\192.168.224.9\\data\\FilewatcherTesting\\STool3\\S_R_S-Tool.csv'
}

@paulmillr Please suggest. Thanks in advance

I cannot even handle the expectation using try..catch

**Comment by paulmillr** [comment]
See other network issues
