### ISSUE TITLE
Chokidar not working on windows 10

### ISSUE THREAD

**Issue by 6ATBA** [paulmillr/chokidar#1222]
**Describe the bug**

Chokidar not working on windows.

**Versions (please complete the following information):**
 - Chokidar version: 3.5.3
 - Node version: 16.13.2, 18.3.0
 - OS version: MacOS 10.15.7, Windows 10 (build 19043.1706)

**To Reproduce:**

1. Make test.js 
```
const { watch } = require('chokidar');

const watcher = watch(".");
watcher.on('ready', () => console.log('Watching dir...'));
watcher.on('change', path => console.log(`File ${path} has been changed`));
```
2. Run "test.js"
3. See error below

```
node:internal/errors:466
    ErrorCaptureStackTrace(err);
    ^

Error: EISDIR: illegal operation on a directory, watch '.'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2306:34)
    at createFsWatchInstance (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:617:16)
    at async Y:\pdf\node_modules\chokidar\index.js:451:21
    at async Promise.all (index 0)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (Y:\pdf\node_modules\chokidar\index.js:647:10)
    at NodeFsHandler._addToNodeFs (Y:\pdf\node_modules\chokidar\lib\nodefs-handler.js:645:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Y:\pdf\node_modules\chokidar\index.js:451:21
    at async Promise.all (index 0) {
  errno: -4068,
  syscall: 'watch',
  code: 'EISDIR',
  path: '.',
  filename: '.'
}
```

**Expected behavior**
The script should work without errors like on MacOS.

**Comment by 6ATBA** [comment]
The problem was in the network drive, indeed.

**Comment by itsdouges** [comment]
What was the solution since it was a network drive? I'm also getting these errors in by users of triplex.dev in Windows. Vite has a similar problem here: https://github.com/vitejs/vite/issues/13655 that was resolved by a try catch. Is Chokidar doing something similar?

<img width="725" alt="image" src="https://github.com/paulmillr/chokidar/assets/6801309/e19fa56f-19a9-41e7-9672-63a8b722bf79">
