### ISSUE TITLE
EACCES: permission denied, watch '/dev/input/event1'

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [paulmillr/chokidar#1243]
**Describe the bug**
I want to detect when a gamepad is connected by watching for `/dev/input/js*` files. This is what happens when I connect a gamepad:
```
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error: EACCES: permission denied, watch '/dev/input/event1'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2301:34)
    at createFsWatchInstance (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:637:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/rajas/gamepad-input/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:645:18) {
  errno: -13,
  syscall: 'watch',
  code: 'EACCES',
  path: '/dev/input/event1',
  filename: '/dev/input/event1'
}
```

**Versions (please complete the following information):**
 - Chokidar version: 3.5.3
 - Node version: v16.17.0
 - OS version: Debian GNU/Linux 11 (bullseye) on a Raspberry Pi 3B V1.2
**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```js
import { watch } from 'chokidar'

watch('/dev/input')
```

**Expected behavior**
Adding / removing gamepads emits 'add' and 'unlink' events. No errors.

**Additional context**
I want to connect a blutooth xbox controller to a raspberry pi and get events for button presses.

**Comment by paulmillr** [comment]
If it's eacces, it's eacces. Google the problem instead of creating chokidar issue
