### ISSUE TITLE
tests fail on Ubuntu 14.04, node v0.10.33

### ISSUE THREAD

**Issue by skinofstars** [paulmillr/chokidar#255]
```
~/projects/chokidar (master) $ npm run test

> chokidar@1.0.0-rc4 test /home/kevin/projects/chokidar
> istanbul test node_modules/mocha/bin/_mocha



  chokidar
    ✓ should expose public API methods 
    non-polling
      watch a directory
        ✓ should produce an instance of chokidar.FSWatcher 
        1) "after each" hook

  2 passing (53ms)
  1 failing

  1) chokidar non-polling watch a directory "after each" hook:
     Uncaught Error: watch ENOSPC
      at errnoException (fs.js:1030:11)
      at FSWatcher.start (fs.js:1062:11)
      at Object.fs.watch (fs.js:1087:11)
      at createFsWatchInstance (/home/kevin/projects/chokidar/lib/nodefs-handler.js:37:15)
      at setFsWatchListener (/home/kevin/projects/chokidar/lib/nodefs-handler.js:77:19)
      at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/kevin/projects/chokidar/lib/nodefs-handler.js:225:14)
      at EventEmitter.NodeFsHandler._handleFile (/home/kevin/projects/chokidar/lib/nodefs-handler.js:252:21)
      at EventEmitter.<anonymous> (/home/kevin/projects/chokidar/lib/nodefs-handler.js:459:21)
      at Object.oncomplete (fs.js:107:15)




events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOSPC
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at createFsWatchInstance (/home/kevin/projects/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/kevin/projects/chokidar/lib/nodefs-handler.js:77:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/kevin/projects/chokidar/lib/nodefs-handler.js:225:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/kevin/projects/chokidar/lib/nodefs-handler.js:252:21)
    at EventEmitter.<anonymous> (/home/kevin/projects/chokidar/lib/nodefs-handler.js:459:21)
    at Object.oncomplete (fs.js:107:15)

npm ERR! chokidar@1.0.0-rc4 test: `istanbul test node_modules/mocha/bin/_mocha`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chokidar@1.0.0-rc4 test script.
npm ERR! This is most likely a problem with the chokidar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     istanbul test node_modules/mocha/bin/_mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls chokidar
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! cwd /home/kevin/projects/chokidar
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kevin/projects/chokidar/npm-debug.log
npm ERR! not ok code 0
```

**Comment by es128** [comment]
It says it can't write the tiny fixture files because there is no space on your disk. That may not be accurate, but it's an issue with your environment, not chokidar or its tests.

**Comment by skinofstars** [comment]
Right you are. I needed to increase inotify max_user_watches. Thanks.
