### ISSUE TITLE
Handle EACCES gracefully

### ISSUE THREAD

**Issue by mixxen** [paulmillr/chokidar#266]
On Ubuntu Linux, one or more files that nodejs does not have read access to in a directory that chokidar is watching will throw an exception:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch EACCES
    at errnoException (fs.js:1031:11)
    at FSWatcher.start (fs.js:1063:11)
    at Object.fs.watch (fs.js:1088:11)
    at createFsWatchInstance (/home/mathnimbus/git/interp/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/mathnimbus/git/interp/node_modules/chokidar/lib/nodefs-handler.js:77:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/mathnimbus/git/interp/node_modules/chokidar/lib/nodefs-handler.js:225:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/mathnimbus/git/interp/node_modules/chokidar/lib/nodefs-handler.js:252:21)
    at EventEmitter.<anonymous> (/home/mathnimbus/git/interp/node_modules/chokidar/lib/nodefs-handler.js:459:21)
    at Object.oncomplete (fs.js:108:15)
```

Possibly have an option to ignore files that do not have read access.

**Comment by es128** [comment]
The error is thrown because you didn't attach a listener to the `error` event on your chokidar instance. As of 67eb99a0ec330eacad0f434640a7a8ada2925ab8 to be included in a forthcoming release very soon, setting `ignorePermissionErrors: true` will also suppress this error from even being emitted.

**Comment by mixxen** [comment]
Sorry, not sure how I missed that. ```ignorePermissionErrors``` works on RC4.
