### ISSUE TITLE
Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by Frenzzy** [paulmillr/chokidar#269]
```
/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289
  return Boolean(4 & parseInt((stats.mode & 0x1ff).toString(8)[0], 10));
                                    ^
TypeError: Cannot read property 'mode' of undefined
    at EventEmitter.FSWatcher._hasReadPermissions (/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/index.js:289:37)
    at EventEmitter.<anonymous> (/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:296:13)
    at FSReqWrap.oncomplete (fs.js:99:15)
```
chokidar 1.0.0-rc4
watchpack 0.2.3
webpack 1.7.3
OS X Yosemite 10.10.2
any thoughts?

**Comment by es128** [comment]
It's fixed in master branch. I'm trying to tie up some loose ends and release rc5 today.

In the meantime, if you're setting `ignorePermissionErrors: true` take that off and it will probably work

**Comment by Frenzzy** [comment]
The use of `ignorePermissionErrors: true` did not help. But problem solved by
```
$ cd node_modules/webpack/node_modules/watchpack/node_modules/
$ npm i git+https://github.com/paulmillr/chokidar.git
```
@es128 thanks!
