### ISSUE TITLE
Memory leak on EventEmitter ?

### ISSUE THREAD

**Issue by felixsanz** [paulmillr/chokidar#297]
Im getting sometimes lot of this errors. I don't usually get them but when i do i get like 10 in the same request. Any idea why this happens?

I'm using nunjucks library which depends on chokidar.

```
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:236:17)
    at Object.fs.watchFile (fs.js:1339:8)
    at EventEmitter.FSWatcher._watch (/home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:251:8)
    at EventEmitter.FSWatcher._handleDir (/home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:351:8)
    at /home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:385:38
    at FSReqWrap.oncomplete (fs.js:78:15)
```

**Comment by paulmillr** [comment]
Seems like invalid usage inside nunjucks. I'll comment there.

**Comment by AndyOGo** [comment]
I get same errors with gulp-watch which depends on chokidar too

**Comment by samejack** [comment]
set usePolling and persistent options is fixed to me
```
chokidar.watch(path, {
    usePolling: true,
    persistent: true
});
```
