### ISSUE TITLE
FreeBSD tests fail with unlink (affecting downstream packages)

### ISSUE THREAD

**Issue by tony** [paulmillr/chokidar#309]
Greetings, I am exploring unreliable behavior with directory watching / closing on FreeBSD (https://github.com/webpack/watchpack/issues/12).  

System information:

```sh
$ uname -apKU
FreeBSD z600 10.2-PRERELEASE FreeBSD 10.2-PRERELEASE #6: Thu Jul  2 04:49:25 CDT 2015     root@z600:/usr/obj/usr/src/sys/MYKERNEL  amd64 amd64 1001519 1001519
```

Here is the test output:

```sh
  chokidar

    ✓ should expose public API methods
    non-polling
      watch a directory

        ✓ should produce an instance of chokidar.FSWatcher

        ✓ should expose public API methods

        ✓ should emit `add` event when file was added

        ✓ should emit `addDir` event when directory was added

        ✓ should emit `change` event when file was changed

        ✓ should emit `unlink` event when file was removed (107ms)

        ✓ should emit `unlinkDir` event when a directory was removed

        ✓ should emit `unlink` and `add` events when a file is renamed (135ms)

        ✓ should not emit `unlink` for previously moved files (575ms)

        ✓ should survive ENOENT for missing subdirectories

        ✓ should notice when a file appears in a new directory
      watch individual files

        ✓ should detect changes

        ✓ should detect unlinks (129ms)

        ✓ should detect unlink and re-add (186ms)

        ✓ should ignore unwatched siblings (335ms)
      watch non-existent paths

        ✓ should watch non-existent file and detect add (332ms)

        ✓ should watch non-existent dir and detect addDir/add (346ms)
      watch glob patterns

        ✓ should correctly watch and emit based on glob input (351ms)

        1) should respect negated glob patterns

        ✓ should traverse subdirs to match globstar patterns (446ms)

        ✓ should resolve relative paths with glob patterns (39ms)

        2) should correctly handle conflicting glob patterns

        ✓ should correctly handle intersecting glob patterns

        ✓ should not confuse glob-like filenames with globs (62ms)

        ✓ should not prematurely filter dirs against complex globstar patterns (354ms)
      watch symlinks

        ✓ should watch symlinked dirs

        ✓ should watch symlinked files

        ✓ should follow symlinked files within a normal dir

        ✓ should watch paths with a symlinked parent (63ms)

        ✓ should not recurse indefinitely on circular symlinks

        ✓ should recognize changes following symlinked dirs (40ms)

        ✓ should follow newly created symlinks (70ms)

        ✓ should watch symlinks as files when followSymlinks:false

        ✓ should watch symlinks within a watched dir as files when followSymlinks:false (75ms)

        ✓ should not reuse watcher when following a symlink to elsewhere (66ms)
      watch options
        ignoreInitial
          false

            ✓ should emit `add` events for preexisting files

            ✓ should emit `addDir` event for watched dir

            ✓ should emit `addDir` events for preexisting dirs
          true

            ✓ should ignore inital add events

            ✓ should ignore add events on a subsequent .add() (630ms)

            ✓ should notice when a file appears in an empty directory

            ✓ should emit a change on a preexisting file as a change

            ✓ should not emit for preexisting dirs when depth is 0 (667ms)
        ignored

          ✓ should check ignore after stating

          ✓ should not choke on an ignored watch path

          ✓ should ignore the contents of ignored dirs (339ms)
        depth

          ✓ should not recurse if depth is 0 (319ms)

          ✓ should recurse to specified depth (345ms)

          ✓ should respect depth setting when following symlinks (965ms)

          ✓ should respect depth setting when following a new symlink (347ms)

          ✓ should correctly handle dir events when depth is 0 (686ms)
        atomic

          ✓ should ignore vim/emacs/Sublime swapfiles (404ms)

          ✓ should ignore stale tilde files
        cwd

          3) should emit relative paths based on cwd

          4) should allow separate watchers to have different cwds
        ignorePermissionErrors
          false

            ✓ should not watch files without read permissions (323ms)
          true

            ✓ should watch unreadable files if possible

            ✓ should not choke on non-existent files
      unwatch

        ✓ should stop watching unwatched paths

        ✓ should ignore unwatched paths that are a subset of watched paths

        ✓ should unwatch relative paths (345ms)
      close

        ✓ should ignore further events on close (315ms)
    polling
      watch a directory

        ✓ should produce an instance of chokidar.FSWatcher

        ✓ should expose public API methods

        ✓ should emit `add` event when file was added (315ms)

        ✓ should emit `addDir` event when directory was added (953ms)

        ✓ should emit `change` event when file was changed (105ms)

        ✓ should emit `unlink` event when file was removed (105ms)

        ✓ should emit `unlinkDir` event when a directory was removed (946ms)

        ✓ should emit `unlink` and `add` events when a file is renamed (942ms)

        ✓ should not emit `unlink` for previously moved files (936ms)

        ✓ should survive ENOENT for missing subdirectories

        ✓ should notice when a file appears in a new directory (960ms)
      watch individual files

        ✓ should detect changes (956ms)

        ✓ should detect unlinks (311ms)

        ✓ should detect unlink and re-add (2156ms)

        ✓ should ignore unwatched siblings (1262ms)
      watch non-existent paths

        ✓ should watch non-existent file and detect add (1248ms)

        ✓ should watch non-existent dir and detect addDir/add (1265ms)
      watch glob patterns

        ✓ should correctly watch and emit based on glob input (1256ms)

        ✓ should respect negated glob patterns (614ms)

        ✓ should traverse subdirs to match globstar patterns (1251ms)

        ✓ should resolve relative paths with glob patterns (936ms)

        ✓ should correctly handle conflicting glob patterns (943ms)

        ✓ should correctly handle intersecting glob patterns (949ms)

        ✓ should not confuse glob-like filenames with globs (1250ms)

        ✓ should not prematurely filter dirs against complex globstar patterns (1237ms)
      watch symlinks

        ✓ should watch symlinked dirs (915ms)

        ✓ should watch symlinked files (944ms)

        ✓ should follow symlinked files within a normal dir (951ms)

        ✓ should watch paths with a symlinked parent (1260ms)

        ✓ should not recurse indefinitely on circular symlinks

        ✓ should recognize changes following symlinked dirs (1012ms)

        ✓ should follow newly created symlinks (1291ms)

        ✓ should watch symlinks as files when followSymlinks:false (910ms)

        ✓ should watch symlinks within a watched dir as files when followSymlinks:false (1253ms)

        ✓ should not reuse watcher when following a symlink to elsewhere (1260ms)
      watch options
        ignoreInitial
          false

            ✓ should emit `add` events for preexisting files

            ✓ should emit `addDir` event for watched dir

            ✓ should emit `addDir` events for preexisting dirs (910ms)
          true

            ✓ should ignore inital add events (907ms)

            ✓ should ignore add events on a subsequent .add() (608ms)

            ✓ should notice when a file appears in an empty directory (70ms)

            ✓ should emit a change on a preexisting file as a change (939ms)

            ✓ should not emit for preexisting dirs when depth is 0 (1567ms)
        ignored

          ✓ should check ignore after stating

          ✓ should not choke on an ignored watch path

          ✓ should ignore the contents of ignored dirs (1217ms)
        depth

          ✓ should not recurse if depth is 0 (310ms)

          ✓ should recurse to specified depth (1236ms)

          ✓ should respect depth setting when following symlinks (1818ms)

          ✓ should respect depth setting when following a new symlink (1259ms)

          ✓ should correctly handle dir events when depth is 0 (2501ms)
        atomic

          ✓ should ignore vim/emacs/Sublime swapfiles (1222ms)

          ✓ should ignore stale tilde files (907ms)
        cwd

          ✓ should emit relative paths based on cwd (1091ms)

          ✓ should allow separate watchers to have different cwds (1363ms)
        ignorePermissionErrors
          false

            ✓ should not watch files without read permissions (307ms)
          true

            ✓ should watch unreadable files if possible

            ✓ should not choke on non-existent files
      unwatch

        ✓ should stop watching unwatched paths (944ms)

        ✓ should ignore unwatched paths that are a subset of watched paths (332ms)

        ✓ should unwatch relative paths (1270ms)
      close

        ✓ should ignore further events on close (305ms)


  121 passing (2m)
  4 failing

  1) chokidar non-polling watch glob patterns should respect negated glob patterns:
     Uncaught expected spy to have been called exactly twice, but it was called once
    spy(add, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809428,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
  AssertionError: expected spy to have been called exactly twice, but it was called once
      spy(add, test-fixtures/unlink.txt, {
    atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809428,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:20:23 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })

  2) chokidar non-polling watch glob patterns should correctly handle conflicting glob patterns:
     Uncaught expected spy to have been called with arguments unlink, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt
    spy(add, /usr/home/tony/work/chokidar/test-fixtures/change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt, {
  atime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809434,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, /usr/home/tony/work/chokidar/test-fixtures/change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
  AssertionError: expected spy to have been called with arguments unlink, test-fixtures/unlink.txt
      spy(add, test-fixtures/change.txt, {
    atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809425,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
  
      spy(add, test-fixtures/unlink.txt, {
    atime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809434,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
  
      spy(change, test-fixtures/change.txt, {
    atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809425,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:20:25 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
      at test.js:506:34
      at finish (test.js:85:7)

  3) chokidar non-polling watch options cwd should emit relative paths based on cwd:
     Uncaught AssertionError: expected spy to have been called with arguments unlink, unlink.txt
    spy(add, change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, unlink.txt, {
  atime: Fri Jul 03 2015 02:20:27 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809443,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:33 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:34 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:34 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:34 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
      at test.js:1096:36
      at finish (test.js:85:7)

  4) chokidar non-polling watch options cwd should allow separate watchers to have different cwds:
     Uncaught AssertionError: expected spy to have been called with arguments unlink, unlink.txt
    spy(add, change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, unlink.txt, {
  atime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809525,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, change.txt, {
  atime: Fri Jul 03 2015 02:20:21 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809425,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:20:35 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
      at test.js:1118:41
      at finish (test.js:85:7)
```

**Comment by tony** [comment]
I should add, this is with io.js 2.3.0.

For posterity, I will also test with node below

**Comment by tony** [comment]
node 2.11.3 is the same.
```
> chokidar@1.0.3 test /usr/home/tony/work/chokidar
> istanbul test node_modules/mocha/bin/_mocha



  chokidar

    ✓ should expose public API methods
    non-polling
      watch a directory

        ✓ should produce an instance of chokidar.FSWatcher

        ✓ should expose public API methods

        ✓ should emit `add` event when file was added

        ✓ should emit `addDir` event when directory was added

        ✓ should emit `change` event when file was changed

        ✓ should emit `unlink` event when file was removed (107ms)

        ✓ should emit `unlinkDir` event when a directory was removed (38ms)

        ✓ should emit `unlink` and `add` events when a file is renamed (133ms)

        ✓ should not emit `unlink` for previously moved files (584ms)

        ✓ should survive ENOENT for missing subdirectories

        ✓ should notice when a file appears in a new directory
      watch individual files

        ✓ should detect changes

        ✓ should detect unlinks (129ms)

        ✓ should detect unlink and re-add (190ms)

        ✓ should ignore unwatched siblings (340ms)
      watch non-existent paths

        ✓ should watch non-existent file and detect add (337ms)

        ✓ should watch non-existent dir and detect addDir/add (344ms)
      watch glob patterns

        ✓ should correctly watch and emit based on glob input (353ms)

        1) should respect negated glob patterns

        ✓ should traverse subdirs to match globstar patterns (447ms)

        ✓ should resolve relative paths with glob patterns

        2) should correctly handle conflicting glob patterns

        ✓ should correctly handle intersecting glob patterns

        ✓ should not confuse glob-like filenames with globs (63ms)

        ✓ should not prematurely filter dirs against complex globstar patterns (358ms)
      watch symlinks

        ✓ should watch symlinked dirs

        ✓ should watch symlinked files

        ✓ should follow symlinked files within a normal dir

        ✓ should watch paths with a symlinked parent (63ms)

        ✓ should not recurse indefinitely on circular symlinks

        ✓ should recognize changes following symlinked dirs (42ms)

        ✓ should follow newly created symlinks (63ms)

        ✓ should watch symlinks as files when followSymlinks:false

        ✓ should watch symlinks within a watched dir as files when followSymlinks:false (66ms)

        ✓ should not reuse watcher when following a symlink to elsewhere (67ms)
      watch options
        ignoreInitial
          false

            ✓ should emit `add` events for preexisting files

            ✓ should emit `addDir` event for watched dir

            ✓ should emit `addDir` events for preexisting dirs
          true

            ✓ should ignore inital add events

            ✓ should ignore add events on a subsequent .add() (622ms)

            ✓ should notice when a file appears in an empty directory

            ✓ should emit a change on a preexisting file as a change

            ✓ should not emit for preexisting dirs when depth is 0 (666ms)
        ignored

          ✓ should check ignore after stating

          ✓ should not choke on an ignored watch path

          ✓ should ignore the contents of ignored dirs (343ms)
        depth

          ✓ should not recurse if depth is 0 (321ms)

          ✓ should recurse to specified depth (358ms)

          ✓ should respect depth setting when following symlinks (950ms)

          ✓ should respect depth setting when following a new symlink (352ms)

          ✓ should correctly handle dir events when depth is 0 (690ms)
        atomic

          ✓ should ignore vim/emacs/Sublime swapfiles (400ms)

          ✓ should ignore stale tilde files
        cwd

          3) should emit relative paths based on cwd

          4) should allow separate watchers to have different cwds
        ignorePermissionErrors
          false

            ✓ should not watch files without read permissions (322ms)
          true

            ✓ should watch unreadable files if possible

            ✓ should not choke on non-existent files
      unwatch

        ✓ should stop watching unwatched paths (42ms)

        ✓ should ignore unwatched paths that are a subset of watched paths

        ✓ should unwatch relative paths (351ms)
      close

        ✓ should ignore further events on close (313ms)
    polling
      watch a directory

        ✓ should produce an instance of chokidar.FSWatcher

        ✓ should expose public API methods

        ✓ should emit `add` event when file was added (315ms)

        ✓ should emit `addDir` event when directory was added (950ms)

        ✓ should emit `change` event when file was changed (107ms)

        ✓ should emit `unlink` event when file was removed (104ms)

        ✓ should emit `unlinkDir` event when a directory was removed (937ms)

        ✓ should emit `unlink` and `add` events when a file is renamed (947ms)

        ✓ should not emit `unlink` for previously moved files (931ms)

        ✓ should survive ENOENT for missing subdirectories

        ✓ should notice when a file appears in a new directory (947ms)
      watch individual files

        ✓ should detect changes (938ms)

        ✓ should detect unlinks (313ms)

        ✓ should detect unlink and re-add (2161ms)

        ✓ should ignore unwatched siblings (1272ms)
      watch non-existent paths

        ✓ should watch non-existent file and detect add (1268ms)

        ✓ should watch non-existent dir and detect addDir/add (1263ms)
      watch glob patterns

        ✓ should correctly watch and emit based on glob input (1259ms)

        ✓ should respect negated glob patterns (632ms)

        ✓ should traverse subdirs to match globstar patterns (1271ms)

        ✓ should resolve relative paths with glob patterns (948ms)

        ✓ should correctly handle conflicting glob patterns (949ms)

        ✓ should correctly handle intersecting glob patterns (930ms)

        ✓ should not confuse glob-like filenames with globs (1257ms)

        ✓ should not prematurely filter dirs against complex globstar patterns (1259ms)
      watch symlinks

        ✓ should watch symlinked dirs (913ms)

        ✓ should watch symlinked files (944ms)

        ✓ should follow symlinked files within a normal dir (946ms)

        ✓ should watch paths with a symlinked parent (1257ms)

        ✓ should not recurse indefinitely on circular symlinks

        ✓ should recognize changes following symlinked dirs (1013ms)

        ✓ should follow newly created symlinks (1295ms)

        ✓ should watch symlinks as files when followSymlinks:false (905ms)

        ✓ should watch symlinks within a watched dir as files when followSymlinks:false (1257ms)

        ✓ should not reuse watcher when following a symlink to elsewhere (1249ms)
      watch options
        ignoreInitial
          false

            ✓ should emit `add` events for preexisting files

            ✓ should emit `addDir` event for watched dir

            ✓ should emit `addDir` events for preexisting dirs (911ms)
          true

            ✓ should ignore inital add events (908ms)

            ✓ should ignore add events on a subsequent .add() (608ms)

            ✓ should notice when a file appears in an empty directory (67ms)

            ✓ should emit a change on a preexisting file as a change (939ms)

            ✓ should not emit for preexisting dirs when depth is 0 (1565ms)
        ignored

          ✓ should check ignore after stating

          ✓ should not choke on an ignored watch path

          ✓ should ignore the contents of ignored dirs (1215ms)
        depth

          ✓ should not recurse if depth is 0 (313ms)

          ✓ should recurse to specified depth (1232ms)

          ✓ should respect depth setting when following symlinks (1820ms)

          ✓ should respect depth setting when following a new symlink (1304ms)

          ✓ should correctly handle dir events when depth is 0 (2497ms)
        atomic

          ✓ should ignore vim/emacs/Sublime swapfiles (1230ms)

          ✓ should ignore stale tilde files (905ms)
        cwd

          ✓ should emit relative paths based on cwd (1067ms)

          ✓ should allow separate watchers to have different cwds (1347ms)
        ignorePermissionErrors
          false

            ✓ should not watch files without read permissions (309ms)
          true

            ✓ should watch unreadable files if possible

            ✓ should not choke on non-existent files
      unwatch

        ✓ should stop watching unwatched paths (938ms)

        ✓ should ignore unwatched paths that are a subset of watched paths (341ms)

        ✓ should unwatch relative paths (1274ms)
      close

        ✓ should ignore further events on close (312ms)


  121 passing (2m)
  4 failing

  1) chokidar non-polling watch glob patterns should respect negated glob patterns:
     Uncaught expected spy to have been called exactly twice, but it was called once
    spy(add, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809172,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
  AssertionError: expected spy to have been called exactly twice, but it was called once
      spy(add, test-fixtures/unlink.txt, {
    atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809172,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:55:44 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })

  2) chokidar non-polling watch glob patterns should correctly handle conflicting glob patterns:
     Uncaught expected spy to have been called with arguments unlink, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt
    spy(add, /usr/home/tony/work/chokidar/test-fixtures/change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, /usr/home/tony/work/chokidar/test-fixtures/unlink.txt, {
  atime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809178,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, /usr/home/tony/work/chokidar/test-fixtures/change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
  AssertionError: expected spy to have been called with arguments unlink, test-fixtures/unlink.txt
      spy(add, test-fixtures/change.txt, {
    atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809169,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
  
      spy(add, test-fixtures/unlink.txt, {
    atime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809178,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
  
      spy(change, test-fixtures/change.txt, {
    atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
    birthtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    blksize: 4096,
    blocks: 1,
    ctime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    dev: 1135203860,
    gid: 1001,
    ino: 5809169,
    mode: 33188,
    mtime: Fri Jul 03 2015 02:55:46 GMT-0500 (CDT),
    nlink: 1,
    rdev: -1,
    size: 1,
    uid: 1001
  })
      at test.js:506:34
      at finish (test.js:85:7)

  3) chokidar non-polling watch options cwd should emit relative paths based on cwd:
     Uncaught AssertionError: expected spy to have been called with arguments unlink, unlink.txt
    spy(add, change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, unlink.txt, {
  atime: Fri Jul 03 2015 02:55:48 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809194,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:54 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
      at test.js:1096:36
      at finish (test.js:85:7)

  4) chokidar non-polling watch options cwd should allow separate watchers to have different cwds:
     Uncaught AssertionError: expected spy to have been called with arguments unlink, unlink.txt
    spy(add, change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(add, unlink.txt, {
  atime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809273,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})

    spy(change, change.txt, {
  atime: Fri Jul 03 2015 02:55:42 GMT-0500 (CDT),
  birthtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  blksize: 4096,
  blocks: 1,
  ctime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  dev: 1135203860,
  gid: 1001,
  ino: 5809169,
  mode: 33188,
  mtime: Fri Jul 03 2015 02:55:56 GMT-0500 (CDT),
  nlink: 1,
  rdev: -1,
  size: 1,
  uid: 1001
})
      at test.js:1118:41
      at finish (test.js:85:7)
```

**Comment by paulmillr** [comment]
Let us know if that still happens with the latest chokidar.
