### ISSUE TITLE
On OSX (fsevents) change event fire in an unexpected way

### ISSUE THREAD

**Issue by sokra** [paulmillr/chokidar#565]
For the watching layer of webpack I wrote a library called watchpack. I wondered why CI on OSX fails and investigated. I. e. I validated some assumptions about chokidars behavior.

One assumption was: If chokidar watcher is created after the file is written I don't get a change event.

Here is the test case: https://github.com/webpack/watchpack/blob/master/test/Assumption.js#L158-L216

This is correct windows and linux, but don't seem to hold on OSX: (from https://travis-ci.org/webpack/watchpack/jobs/185772019)

``` text
Assumption
  ...
  ✓ should fire events not after start and 1000ms delay (1502ms)
  ✓ should fire events not after start and 700ms delay (1202ms)
  ✓ should fire events not after start and 500ms delay (1006ms)
  ✓ should fire events not after start and 300ms delay (803ms)
  ✓ should fire events not after start and 200ms delay (703ms)
  ✓ should fire events not after start and 100ms delay (611ms)
  ✓ should fire events not after start and 50ms delay (558ms)
  ✓ should fire events not after start and 20ms delay (524ms)
  ✓ should fire events not after start and 10ms delay (514ms)
  ✓ should fire events not after start and 5ms delay (516ms)
  1) should fire events not after start and 1ms delay
  2) should fire events not after start and 0ms delay
  3) should not fire events after start

  1) Assumption should fire events not after start and 1ms delay:
     Error: should not be emitted /Users/travis/build/webpack/watchpack/test/fixtures/watch-test-file-1
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/test/Assumption.js:176:11)
      at emitTwo (events.js:87:13)
      at FSWatcher.emit (events.js:172:7)
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:191:15)
      at /Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:230:7
      at FSReqWrap.oncomplete (fs.js:82:15)
  2) Assumption should fire events not after start and 0ms delay:
     Error: should not be emitted /Users/travis/build/webpack/watchpack/test/fixtures/watch-test-file-0
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/test/Assumption.js:176:11)
      at emitTwo (events.js:87:13)
      at FSWatcher.emit (events.js:172:7)
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:191:15)
      at /Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:230:7
      at FSReqWrap.oncomplete (fs.js:82:15)
  3) Assumption should not fire events after start:
     Error: should not be emitted /Users/travis/build/webpack/watchpack/test/fixtures/watch-test-file-a
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/test/Assumption.js:206:9)
      at emitTwo (events.js:87:13)
      at FSWatcher.emit (events.js:172:7)
      at FSWatcher.<anonymous> (/Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:191:15)
      at /Users/travis/build/webpack/watchpack/node_modules/chokidar/index.js:230:7
      at FSReqWrap.oncomplete (fs.js:82:15)
```

Am I wrong with this assumption or should I consider this as bug?

**Comment by es128** [comment]
If I understand what you're showing here correctly, you're testing the fsevents reporting more so than chokidar. I don't really have an explanation for why the `change` event seems to "echo" in that way and show up even if the watcher is added immediately afterward.

If we could come up with a way to reliably suppress these events as misreported, then it could be something chokidar takes control of - but how would we tell the difference between valid and invalid events?

If the only impact here is in your test suite, then I suggest implementing sufficient delays there to prevent problems. I've struggled with the chokidar tests similarly. Testing with actual file system actions is more of an integration test than unit testing, and file systems behave inconsistently. Running through a test suite tends to stress it more than other typical use cases.

Also, I've had tons of problems with testing on OS X with Travis that don't manifest locally or anywhere else, and I've never been able to fully resolve. At some times it's worse than others. Seems to just have something to do with their VM infrastructure, and again, that we're running integration tests with a variety of disparate flaky file system implementations, not logical unit tests.
