### ISSUE TITLE
Tests failing on Node.js 8 🔥

### ISSUE THREAD

**Issue by swashcap** [paulmillr/chokidar#607]
* **Node.js:** 8.0.0
* **npm:** 5.0.1
* **OS:** OS X 10.12.5

chokidar’s tests fail on Node.js 8.0.0 on current master (3d917818c957088b62c160e426c1a99787ae6319). The failing ones:

```
  1) chokidar fsevents (native extension) watch options awaitWriteFinish should emit an unlink event when a file is updated and deleted just after that:
     Uncaught Error: ENOENT: no such file or directory, unlink '/Users/creed/Sites/chokidar/test-fixtures/84/subdir/add.txt'
  

  2) chokidar fs.watch (non-polling) watch a directory should emit `add` event when file was added:
     Uncaught expected spy to have been called with arguments unlink, add.txt
    spy(addDir, ) at emitTwo (events.js:125:13)
  AssertionError: expected spy to have been called with arguments unlink, add.txt
      at test.js:1660:42
      at Timeout.finish (test.js:157:7)

  3) chokidar fs.watch (non-polling) watch a directory should emit `addDir` event when directory was added:
     Uncaught AssertionError: expected rawSpy to have been called at least once, but it was never called
      at test.js:201:34
      at finish (test.js:157:7)
      at Timeout.<anonymous> (test.js:161:36)

  4) chokidar fs.watch (non-polling) watch individual files should detect unlink and re-add:
     Uncaught AssertionError: expected spy to have been called exactly once, but it was called 0 times
      at test.js:213:31
      at Timeout.finish (test.js:157:7)

  5) chokidar fs.watch (non-polling) watch glob patterns should not prematurely filter dirs against complex globstar patterns:
     Uncaught AssertionError: expected spy to have been called exactly once, but it was called 0 times
      at test.js:470:37
      at Timeout.finish (test.js:157:7)

  6) chokidar fs.watch (non-polling) watch arrays of paths/globs should watch all paths in an array:
     Error: EEXIST: file already exists, mkdir '/Users/creed/Sites/chokidar/test-fixtures/132/subdir'
      at Object.fs.mkdirSync (fs.js:877:18)
      at Context.<anonymous> (test.js:964:10)
      at node_modules/graceful-fs/graceful-fs.js:99:16
      at node_modules/graceful-fs/graceful-fs.js:43:10
      at node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
      at FSReqWrap.oncomplete (fs.js:135:15)

  7) chokidar fs.watch (non-polling) watch symlinks should follow symlinked files within a normal dir:
     Error: ENOENT: no such file or directory, symlink '/Users/creed/Sites/chokidar/test-fixtures/135/change.txt' -> '/Users/creed/Sites/chokidar/test-fixtures/135/subdir/link.txt'
      at Object.fs.symlinkSync (fs.js:1006:18)
      at Context.<anonymous> (test.js:819:10)

  8) chokidar fs.watch (non-polling) watch symlinks "before each" hook for "should follow symlinked files within a normal dir":
     Error: ENOENT: no such file or directory, open '/Users/creed/Sites/chokidar/test-fixtures/136/subdir/add.txt'
  

  9) chokidar fs.watch (non-polling) watch symlinks should watch paths with a symlinked parent:
     Uncaught AssertionError: expected spy to have been called with arguments addDir, /Users/creed/Sites/chokidar/test-fixtures/134-link/subdir
      at FSWatcher.<anonymous> (test.js:838:32)
      at _combinedTickCallback (internal/process/next_tick.js:95:7)
      at process._tickCallback (internal/process/next_tick.js:161:9)
```

Full output here: https://gist.github.com/swashcap/b4bbfc8c1dccc0af2e98bebb587954fc

**Comment by swashcap** [comment]
What would you think of trying to add chokidar to https://github.com/nodejs/citgm ? This would smoke test chokidar against upcoming Node.js versions, and wouldn’t require additional work from maintainers other than the usual bug fixes. I’d be happy to [make a PR and submit it](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm).

**Comment by cjrutherford** [comment]
Is this still being worked on? I'm developing on Node 8. Just want to be sure before rolling back to node 6.

On Node 8.1.4, using the code from the readme just exits after running. Not getting errors, but not working either.

**Comment by es128** [comment]
I only just added node 8 to the CI configs, but all the tests are passing. [OS X](https://travis-ci.org/paulmillr/chokidar/jobs/256276495), [Linux](https://travis-ci.org/paulmillr/chokidar/jobs/256276494), [Windows](https://ci.appveyor.com/project/es128/chokidar/branch/master/job/tra48ngv34vluedg)
