### ISSUE TITLE
After an exception occurs, file wather became invalid

### ISSUE THREAD

**Issue by clancytom** [paulmillr/chokidar#650]
```js
const chokidar = require('chokidar');
let watch = chokidar.watch(`/server/**/*.js`, { persistent: true, ignoreInitial: true });
watch.on('add', path =>{
    console.info(`Add file ${path}`);
}).on('unlink', path =>{
    console.info(`Unlink file ${path}`);
}).on('error', (error)=>{
    console.error(`watcher Error , ${error}`);
})
```
> I delete the folder /server
```js
Unlink file /server/mochawesome-report/test/gadgets/a.js
Unlink file /server/mochawesome-report/test/gadgets/b.js
watcher Error , Error: EPERM: operation not permitted, lstat ' /server/mochawesome-report'
watcher Error , Error: EPERM: operation not permitted, lstat ' /server/mochawesome-report'
```
> then I create the server folder ,and add some js file ,but the water is Not effective

**Comment by Simran-B** [comment]
This seems to crash `gitbook serve`:

```
Starting server ...
Serving book on http://localhost:4000
Restart after change in file FrontMatter.md

Stopping server
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'C:\Users\Simran\Projekte\ArangoDB\support\gitbook3\Manual\_book'
Emitted 'error' event at:
    at FSWatcher._handleError (C:\Users\Simran\.gitbook\versions\3.2.2\node_modules\chokidar\index.js:236:10)
    at ReaddirpReadable.emit (events.js:182:13)
    at Immediate.<anonymous> (C:\Users\Simran\.gitbook\versions\3.2.2\node_modules\chokidar\node_modules\readdirp\stream-api.js:83:32)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.

**Comment by Simran-B** [comment]
Gitbook is dead unfortunately. Thanks for the update nonetheless.
