### ISSUE TITLE
Inconsistent `.getWatched()` results macOs vs Linux

### ISSUE THREAD

**Issue by mhkeller** [paulmillr/chokidar#652]
When I do `.getWatched()`, I am getting inconsistent results from macOs versus Travis. I made a test repo here: https://github.com/mhkeller/chokidar-test which points to the travis output.

When this script runs locally on macOs 10.11.6 (edit: and on Travis under an OS X build), it correctly outputs the following

```js
{
  '/Users/redacted/test/chokidar-test/files': [ 'subdir', 'test.txt' ],
  '/Users/redacted/test/chokidar-test/files/subdir': [ 'file-2.txt' ]
}
```

When I run this on Travis in a Linux environment, I get the following

```js
{
  '/home/travis/build/mhkeller/chokidar-test': [ 'files' ],
  '/home/travis/build/mhkeller/chokidar-test/files': [ 'subdir', 'test.txt' ],
  '/home/travis/build/mhkeller/chokidar-test/files/**/*': [],
  '/home/travis/build/mhkeller/chokidar-test/files/subdir': [ 'file-2.txt' ]
}
```

Travis results: https://travis-ci.org/mhkeller/chokidar-test/jobs/303238599

Why are the `files` folder and the glob showing up? I tried doing `cwd: __dirname` and `cwd: path.resolve('./')` but it doesn't fix it.

**Comment by mhkeller** [comment]
I imagine this might have to do with FSEvents not working on Linux. Standardizing output between the platform, though, would be helpful.

**Comment by es128** [comment]
I agree that this is a bug. It's most likely caused by inconsistencies between fsevents-handler.js and nodefs-handler.js, not directly caused by the `fsevents` dependency.

**Comment by mhkeller** [comment]
@es128 Thanks for taking a look. Do you have a sense of where this would fit on the roadmap? Just wondering to help me figure out when I can update my workaround for this.

**Comment by es128** [comment]
@mhkeller I'll try to make time available to review any solutions submitted as a PR by someone in the community. If nobody steps up to do that it is not likely this will get worked on.

**Comment by mhkeller** [comment]
I [did some digging](https://github.com/mhkeller/chokidar/commit/ddbeb7b068d979166c226ef15ac0a20228cbc687) into this. It seems to happen when you pass a glob like `path/to/**/*` and I think the problem has to do this this line in `nodefs-hander.js` where ` this._getWatchedDir` is being called with `wh.path`

https://github.com/paulmillr/chokidar/blob/df88ff0d001eefc0565c8311302ee127737c476e/lib/nodefs-handler.js#L353

If you have a glob, `wh.path` will include that glob and so when it gets sent to `this._getWatchedDir`, it will construct the tree with that as the root directory. I tried replacing `wh.path` with `wh.watchPath` which is the sanitized version, but that causes a number of other tests to break (see below)

If you have any pointers from here @es128, I'll keep looking into it. I also added [a test here](https://github.com/mhkeller/chokidar/commit/ddbeb7b068d979166c226ef15ac0a20228cbc687#diff-1dd241c4cd3fd1dd89c570cee98b79ddR1773) that catches this behavior.

---

Here are the tests that break when I switch it to `wh.watchPath` for reference. Note: tests 5 and 7 were failing on a fresh clone so those aren't caused by this.

```
  1) chokidar fsevents (native extension) watch options awaitWriteFinish should emit an unlink event when a file is updated and deleted just after that:
     Error: done() called multiple times
      at it (test.js:52:13)
      at Suite.<anonymous> (test.js:1686:7)
      at Suite.<anonymous> (test.js:1526:5)
      at Suite.runTests (test.js:1041:3)
      at Suite.<anonymous> (test.js:114:5)
      at Object.<anonymous> (test.js:106:1)
      at require (internal/module.js:11:18)
      at Array.forEach (<anonymous>)
      at runFn (node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
      at Object.run (node_modules/istanbul/lib/command/common/run-with-cover.js:254:9)
      at TestCommand.run (node_modules/istanbul/lib/command/test.js:27:22)
      at runCommand (node_modules/istanbul/lib/cli.js:78:19)
      at runToCompletion (node_modules/istanbul/lib/cli.js:82:5)
      at Object.<anonymous> (node_modules/istanbul/lib/cli.js:88:5)
      at startup (bootstrap_node.js:187:16)
      at bootstrap_node.js:608:3

  2) chokidar fsevents (native extension) watch options awaitWriteFinish should emit an unlink event when a file is updated and deleted just after that:
     Error: done() called multiple times
      at it (test.js:52:13)
      at Suite.<anonymous> (test.js:1686:7)
      at Suite.<anonymous> (test.js:1526:5)
      at Suite.runTests (test.js:1041:3)
      at Suite.<anonymous> (test.js:114:5)
      at Object.<anonymous> (test.js:106:1)
      at require (internal/module.js:11:18)
      at Array.forEach (<anonymous>)
      at runFn (node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
      at Object.run (node_modules/istanbul/lib/command/common/run-with-cover.js:254:9)
      at TestCommand.run (node_modules/istanbul/lib/command/test.js:27:22)
      at runCommand (node_modules/istanbul/lib/cli.js:78:19)
      at runToCompletion (node_modules/istanbul/lib/cli.js:82:5)
      at Object.<anonymous> (node_modules/istanbul/lib/cli.js:88:5)
      at startup (bootstrap_node.js:187:16)
      at bootstrap_node.js:608:3

  3) chokidar fsevents (native extension) unwatch should ignore unwatched paths that are a subset of watched paths:
     Uncaught expected spy to have been called exactly once, but it was called twice
    spy(addDir, /Users/mhk/wrk/code/chokidar/test-fixtures/91/subdir) at emitTwo (events.js:126:13)
    spy(change, /Users/mhk/wrk/code/chokidar/test-fixtures/91/change.txt) at emitTwo (events.js:126:13)
  AssertionError: expected spy to have been called exactly once, but it was called twice
      at Timeout._onTimeout (test.js:1841:51)

  4) chokidar fs.watch (non-polling) watch a directory should watch removed and re-added directories:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  5) chokidar fs.watchFile (polling) watch individual files should detect unlink and re-add:
     Uncaught AssertionError: expected addSpy to have been called with arguments /Users/mhk/wrk/code/chokidar/test-fixtures/115/subdir2/subsub%D
      at test.js:392:39
      at Timeout.finish (test.js:167:7)

  6) chokidar fs.watchFile (polling) watch glob patterns should correctly handle glob with braces:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  7) chokidar fs.watch (non-polling) watch individual files should detect unlink and re-add:
     Uncaught AssertionError: expected addSpy to have been called with arguments /Users/mhk/wrk/code/chokidar/test-fixtures/131/unlink.txt%D
      at test.js:441:39
      at Timeout.finish (test.js:167:7)

  8) chokidar fs.watch (non-polling) watch options "before all" hook: closeWatchers:
     Uncaught AssertionError: expected addSpy to have been called with arguments /Users/mhk/wrk/code/chokidar/test-fixtures/150/unlink.txt%D
      at test.js:441:39
      at Timeout.finish (test.js:167:7)

  9) chokidar fs.watch (non-polling) watch options ignored should check ignore after stating:
     Error: EEXIST: file already exists, mkdir '/Users/mhk/wrk/code/chokidar/test-fixtures/182/subdir'
      at Object.fs.mkdirSync (fs.js:885:18)
      at Context.<anonymous> (test.js:1165:12)

  10) chokidar fs.watch (non-polling) watch options cwd should emit `addDir` with alwaysStat for renamed directory:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  11) chokidar fs.watchFile (polling) watch options ignoreInitial true should ignore add events on a subsequent .add():
     Uncaught AssertionError: expected spy to have been called exactly once, but it was called 0 times
      at test.js:1412:38
      at Timeout.finish (test.js:167:7)

  12) chokidar fs.watchFile (polling) watch options ignored should ignore the contents of ignored dirs:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  13) chokidar fs.watch (non-polling) watch options ignorePermissionErrors false should not watch files without read permissions:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  14) chokidar fs.watch (non-polling) watch options ignorePermissionErrors false "before each" hook for "should watch unreadable files if possible":
     TypeError: Cannot read property 'call' of undefined

```

**Comment by es128** [comment]
What happens if you give it the glob parent of `wh.path`?

**Comment by mhkeller** [comment]
Hm I don't fully understand. Like if the path I'm giving to chokidar is `path/to/**/*` then you're asking what if I set `previous` to `'path/to'`? When I do `var previous = this._getWatchedDir(wh.watchPatch)`, then `wh.watchPatch` is equal to `'path/to'`,

**Comment by paulmillr** [comment]
3.x should resolve this
