### ISSUE TITLE
Error on file addition.

### ISSUE THREAD

**Issue by ballatom** [paulmillr/chokidar#738]
Hi,

I get the following error while watching a backup directory on a Proxmox host :

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /var/lib/vz/backup/dump/vzdump-lxc-106-2018_06_18-17_09_39.tmp/usr/share/cmake-3.7/Modules/CMakeBackwardCompatibilityCXX.cmake ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/ballama/Projects/proxmox_backup_manager/nodejs/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ballama/Projects/proxmox_backup_manager/nodejs/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ballama/Projects/proxmox_backup_manager/nodejs/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/ballama/Projects/proxmox_backup_manager/nodejs/node_modules/chokidar/lib/nodefs-handler.js:259:21)
    at FSWatcher.<anonymous> (/home/ballama/Projects/proxmox_backup_manager/nodejs/node_modules/chokidar/lib/nodefs-handler.js:480:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
```
I have noticed that Chokidar requires escaped filenames as opposed to packages like fs.  This is a bit annoying as it requires me to maintain both an escaped and a non-escaped version of the same filename in my programs.  However this cannot be the cause for this error, though there is a whitespace at the end of the filename as I watch files with spaces in another program without error.

Any idea why I get it here ?

Cheers,

Marc

**Comment by srguiwiz** [comment]
@ballatom, please provide version number of chokidar and node in use.

**Comment by es128** [comment]
> I have noticed that Chokidar requires escaped filenames as opposed to packages like fs

Not sure what you're referring to here, you do not need to escape filenames. If you want to ensure there is no intersection with glob interpretation of your file path strings you can use the `disableGlobbing: true` option.

The part you're describing about whitespace at the end of the filename sounds odd, please show more details on that point if it's the source of your difficulty. Even in a shell you'd need to do some special escaping of that space character in the filename. 

The ENOSPC error likely has to do with system limits on watchers, you can read more about how to resolve that at https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
