### ISSUE TITLE
Error while building sass assets

### ISSUE THREAD

**Issue by konart** [paulmillr/chokidar#869]
Coming here from: https://github.com/sass/dart-sass/issues/748

**Describe the bug**
An error occurs while trying to build sass assets with [sass](https://github.com/sass/dart-sass)

```
/var/www/xxx/xxx/node_modules/chokidar/index.js:121
  async remove(item) {
        ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/xxx/xxx/node_modules/sass/sass.dart.js:72:17)
```

**Versions (please complete the following information):**
 - Chokidar version 3.0.2
 - Debian 3.16.36-1+deb8u2

**Comment by paulmillr** [comment]
You’ve forgot to mention your node.js version.

**Comment by konart** [comment]
`node -v`
v6.10.2

**Comment by paulmillr** [comment]
You will need to upgrade to node 8 / 10 / 12; or pick a node-sass version which supports nodejs v6. That's it!

**Comment by paulmillr** [comment]
BTW, engines.node is shit.
