### ISSUE TITLE
Improper handling of broken symlinks, causes UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jaens** [paulmillr/chokidar#955]
When watching a directory with `followSymlinks` off, if the directory contains links for which the target does not exist, chokidar blows up with:

```
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat <path of symlink>
```

This is due to calling `fsrealpath` on the link, which fails (since the link target does not exist) here:
https://github.com/paulmillr/chokidar/blob/7c79e45f83b52084d03940ed882e0279e1c23b5f/lib/nodefs-handler.js#L416

Note the node.js documentation for `fs.realpath`:
> Asynchronously computes the canonical pathname by resolving ., .. and **symbolic links**.

Perhaps using the `path` module would be more appropriate there.

**Comment by jaens** [comment]
Looks like `fsrealpath` is also being used in a similar manner here:
https://github.com/paulmillr/chokidar/blob/7c79e45f83b52084d03940ed882e0279e1c23b5f/lib/nodefs-handler.js#L607

**Comment by ruruiye** [comment]
same problem here

**Comment by paulmillr** [comment]
pull requests are welcome

**Comment by nicks** [comment]
fwiw, this breaks create-react-app's webpack server hard, because it treats these warnings as errors and crashes the server

The error looks like this:

```
/home/nick/src/tilt/web/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat '/home/nick/src/tilt/web/src/.#Statusbar.tsx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/nick/src/tilt/web/src/.#Statusbar.tsx'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Here's the stack trace to the call that throws the error.

```
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at NodeFsHandler._handleSymlink (/home/nick/src/tilt/web/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:433:30)
    at ReaddirpStream.<anonymous> (/home/nick/src/tilt/web/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:486:23)
    at ReaddirpStream.emit (events.js:321:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ReaddirpStream.Readable.push (_stream_readable.js:209:10)
```

I'm happy to send a PR, but is there some reason this isn't as simple as wrapping the unhandled await call in a `try...catch` block? I'm probably missing something.

**Comment by paulmillr** [comment]
try adding try catch, adding the failing test, and seeing if that breaks any other tests
